version: '3.8'


services:
  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    user: root
    restart: unless-stopped
    network_mode: host
    # environment:
    #   GF_PATHS_CONFIG: "/etc/grafana/grafana.ini"

    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana:rw"
      # - "${PWD-.}/:/etc/grafana"

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: unless-stopped
  #   user: root
  #   network_mode: host
  #   volumes:
  #     - ${PWD-.}/prometheus.yml:/etc/prometheus/prometheus.yml:rw
  #     - ${PWD-.}/prometheus_data:/prometheus:rw
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #     - '--web.enable-lifecycle'

  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    network_mode: host
    
    volumes:
      - "$PWD/influxdb/data:/var/lib/influxdb2" 
      - "$PWD/influxdb/config:/etc/influxdb2" 