version: '3.8'

services:

  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    user: root
    restart: unless-stopped
    network_mode: host
    # environment:
    #   GF_PATHS_CONFIG: "/etc/grafana/grafana.ini"
    volumes:
      - "$PWD/grafana:/var/lib/grafana:rw"

  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    network_mode: host
    volumes:
      - "$PWD/influxdb/data:/var/lib/influxdb2" 
      - "$PWD/influxdb/config:/etc/influxdb2" 

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    network_mode: host
    volumes:
        - "$PWD/telegraf:/etc/telegraf"
